Esri/ember-arcgis-portal-services

- package.json
- tests/dummy/config/environment.js
Since this is about tooling not functionality, not sure it gets a changelog and def should not get a verion bump / release...
> added surge deploys and contributors

- CHANGELOG.md
- README.md
- addon/services/items-service.js
- addon/utils/get-image-as-blob.js
- app/get-image-as-blob/util.js
- package.json
- tests/unit/utils/get-image-as-blob-test.js
Adds itemsService.addImageFromUrlAsResource
Fixes issue with deploying to devext
> [DNM] copied methods from opendata-admin

- package.json
- tests/dummy/app/items/item/edit/route.js
Changes in Dummy App
- whitelist mapservice to fetch json,
- handle empty json responses
- deploy to prod will deploy to eaps.surge.sh as well as eapsprod.surge.sh
> Map Service /data

- CHANGELOG.md
- addon/services/items-service.js
- tests/dummy/app/components/file-input/component.js
- tests/dummy/app/components/item-resources/template.hbs
- tests/dummy/app/items/item/edit/controller.js
- tests/dummy/app/items/item/edit/template.hbs
- tests/dummy/config/environment.js
`uploadThumbnail (itemId, owner, blob, filename, portalOpts)`
Also adds this into the dummy app
> Added items-service.uploadThumbnail fn

- CHANGELOG.md
- addon/mixins/service-mixin.js
- package.json
- tests/dummy/app/components/item-resources/component.js
- tests/dummy/app/items/item/edit/controller.js
Also adds a really cheeky `.catch` in the item editor so we see errors.
> remove ember-network, add ember-fetch

- README.md
- config/environment.js
- testem.js
> get tests running on travis

- addon/services/sharing-service.js
- package-lock.json
- tests/unit/services/sharing-service-test.js
the 'items' parameter is only valid for the bulk operations [`/shareItems`](https://developers.arcgis.com/rest/users-groups-and-items/share-items.htm) and [`unshareItems`](https://developers.arcgis.com/rest/users-groups-and-items/unshare-items.htm).
it is ignored by [`/share`](https://developers.arcgis.com/rest/users-groups-and-items/share-item-as-item-owner-.htm) and [`/unshare`](https://developers.arcgis.com/rest/users-groups-and-items/unshare-item-as-item-owner-.htm).
> remove items param, which is ignored by <item-url>/un/share

- CHANGELOG.md
- ember-cli-build.js
- tests/dummy/app/application/route.js
- tests/dummy/config/environment.js
This allows the Dummy app to be used in IE/Edge
> load fetch via polyfill.io for the Dummy App

- CHANGELOG.md
- addon/services/items-service.js
- package-lock.json
> remove unused private methods

- CHANGELOG.md
- package-lock.json
- package.json
related: https://github.com/ArcGIS/opendata-ui/issues/3232
> bump torii to 1.1.6 to ensure UserSessions are instantiated correctly from cookies

- .eslintrc.js
- CHANGELOG.md
- addon/services/portal-service.js
- addon/utils/fetch-image-as-blob.js
https://esriarlington.tpondemand.com/entity/86115-eaps-use-eslint-no-restricted-globals
> don't use global fetch

- addon/services/groups-service.js
- package-lock.json
- tests/dummy/app/groups/group/route.js
- tests/dummy/app/groups/group/template.hbs
- tests/dummy/app/groups/new/controller.js
- tests/unit/mixins/service-mixin-test.js
resolves #117 
threw @tomwayson a bone toward #129 as well.
full disclosure. there were zero unit tests here for groups to begin with and the dummy app only has UI elements to exercise ~75% of the affected functions.
if you want me to npm link the branch and run e2e, just say the word.
> call out to arcgis-rest-groups for get, create, update, search, remove, protect, etc.

- CHANGELOG.md
- addon/mixins/service-mixin.js
- addon/services/user-service.js
Adds ability to make multipart/form-data requests from users service.
> users-service multipart/form-data requests

- tests/dummy/app/items/item/edit/route.js
Just updates the Dummy app to allow a Solution item to display it's "data"
> Show the Solution items data

- README.md
this will help my addons section for the workshop
> Say that this is a wrapper around arcgis-rest-js

- CHANGELOG.md
- README.md
- addon/services/portal-service.js
add setUserDefaultSettins to portal-service.
[Story](https://esriarlington.tpondemand.com/entity/89149-activation-sets-email-based-logins-for)
[Story](https://esriarlington.tpondemand.com/entity/89148-administrator-sets-platform-sso-and-email)
> setUserDefaultSettings

- CHANGELOG.md
- addon/services/sharing-service.js
- package.json
- yarn.lock
> pass through confirmItemControl correctly 🤕

- CHANGELOG.md
- addon/services/groups-service.js
- package.json
- yarn.lock
> use rest-js in addUsers() and addAdmins() method of groups-service

- tests/dummy/app/items/index/controller.js
- tests/dummy/app/items/index/route.js
not sure why this was failing, but this fixes it for now
> ensure a default query

- CHANGELOG.md
- addon/services/items-service.js
- addon/services/user-service.js
- package.json
- yarn.lock
to integrate new functions from https://github.com/Esri/arcgis-rest-js/pull/613 and https://github.com/Esri/arcgis-rest-js/pull/614
> F/add latest functions from arcgis-rest-js v2.4.0

- CHANGELOG.md
- addon/services/portal-service.js
- This new `removeSocialProviders ` function supports this PR in opendata-ui: https://github.com/ArcGIS/opendata-ui/pull/5702
- Fix typo in `configureSocialProviders` comment
> Add remove social providers function

- addon/services/items-service.js
- tests/unit/services/items-service-test.js
Updating export to support additional params.
> Export Additional Params
